#!/usr/bin/env python3
"""Embed the basic-pitch model into a C++ header at build time.

Turns the ONNX model (`nmp.onnx`, referenced in place from the
`external/basic-pitch` submodule) into a header of raw bytes that the C++
`OnnxSession::loadFromMemory` parses directly, so the shipping binary needs no
model file on disk at runtime.

The manifest (`manifests/basic-pitch.txt`) is the single source of truth for
provenance. Before emitting anything, the generator hashes the model and
FAILS THE BUILD if the SHA-256 does not match the manifest's `model_sha256` —
a guard against a drifted submodule pin.

Usage:
    nmp_onnx_to_header.py <nmp.onnx> <manifest.txt> <out.h>

The header is emitted into the build tree (git-ignored) by CMake; it is not a
checked-in source file.
"""

import hashlib
import sys
from pathlib import Path


def parse_manifest(path):
    """Read `key = value` lines, ignoring blank lines and `#` comments.

    An inline `# ...` trailing comment after the value is stripped, so a line
    like `submodule_pin = <sha>   # "..."` yields just the `<sha>`.
    """
    fields = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        fields[key.strip()] = value.split("#", 1)[0].strip()
    return fields


def main():
    if len(sys.argv) != 4:
        print(
            "usage: nmp_onnx_to_header.py <nmp.onnx> <manifest.txt> <out.h>",
            file=sys.stderr,
        )
        return 1
    onnx_path, manifest_path, out_path = (Path(a) for a in sys.argv[1:4])

    data = onnx_path.read_bytes()
    actual = hashlib.sha256(data).hexdigest()

    m = parse_manifest(manifest_path)
    expected = m.get("model_sha256")
    if expected is None or actual != expected:
        print(
            f"ERROR: nmp.onnx SHA-256 {actual} != manifest {expected} "
            f"({onnx_path})",
            file=sys.stderr,
        )
        return 1

    # Attribution, all drawn from the manifest (single source of truth).
    prov = (
        f"//   Model      : Spotify basic-pitch, ICASSP 2022 'nmp'. "
        f"{m.get('license', 'Apache-2.0')}\n"
        f"//   Paper      : \"A Lightweight Instrument-Agnostic Model for Polyphonic\n"
        f"//               Note Transcription and Multipitch Estimation\" — Bittner,\n"
        f"//               Bosch, Rubinstein, Meseguer-Brocal, Ewert. ICASSP 2022.\n"
        f"//   Upstream   : {m.get('upstream', 'https://github.com/spotify/basic-pitch')}\n"
        f"//   Pinned at  : {m.get('submodule_pin', '')}\n"
        f"//   Converted  : {m.get('converted_by', 'tf2onnx (upstream)')}\n"
        f"//   SHA-256    : {expected}  (verified against the manifest at build time)\n"
    )

    # Wrap the byte array ~20 bytes per line so the (build-tree) header stays
    # readable. The trailing comma is legal C++ and keeps every line uniform.
    lines = [", ".join(f"0x{b:02x}" for b in data[i : i + 20])
             for i in range(0, len(data), 20)]

    header = (
        "// ===========================================================================\n"
        "// nmp_onnx_data.h — AUTO-GENERATED AT BUILD TIME. DO NOT EDIT.\n"
        "// Generated by libaudio/tools/nmp_onnx_to_header.py from the\n"
        "// external/basic-pitch submodule (referenced in place). The generator\n"
        "// fails the build if the model's SHA-256 does not match the manifest.\n"
        f"{prov}"
        "//\n"
        "// The bytes are parsed directly by ONNX Runtime (the in-memory\n"
        "// Ort::Session constructor) so the model needs no file on disk at\n"
        "// runtime.\n"
        "// ===========================================================================\n"
        "\n"
        "#ifndef LIBAUDIO_NMP_ONNX_DATA_H\n"
        "#define LIBAUDIO_NMP_ONNX_DATA_H\n"
        "\n"
        "#include <cstddef>\n"
        "\n"
        "namespace libaudio {\n"
        "\n"
        f"// The full serialized ONNX model: {len(data)} bytes.\n"
        "// `inline const` (not `constexpr`): the array is too large for some\n"
        "// compilers to keep as a compile-time constant, but `inline` gives it\n"
        "// external linkage so the linker dedupes the per-translation-unit\n"
        "// copies into a single object in the final binary.\n"
        "inline const unsigned char nmp_onnx[] = {\n"
        + ",\n".join("   " + l for l in lines)
        + ",\n"
        "};\n"
        "\n"
        "inline constexpr std::size_t nmp_onnx_len = sizeof(nmp_onnx);\n"
        "\n"
        "} // namespace libaudio\n"
        "\n"
        "#endif // LIBAUDIO_NMP_ONNX_DATA_H\n"
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header, encoding="utf-8")
    print(f"OK: embedded {len(data)} bytes -> {out_path} (sha256 {expected})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
